name: Test Sandbox

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-sandbox:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install package
      run: pip install -e .
    
    - name: Test CLI help
      run: python -m nkd_agents help
    
    - name: Test Docker image build
      run: docker build -t nkd_agents:latest .
    
    - name: Test container runs
      run: |
        echo "print('Hello from container!')" > test.py
        docker run --rm -v $(pwd):/workspace nkd_agents:latest python test.py
    
    - name: Test sandbox command (without API key)
      run: python -m nkd_agents sandbox || true  # Expected to fail without API key